# -*- coding: utf-8 -*-
"""Taller

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ieKUTCwwsO5CQgM8h--RThnMTZuigMT

**Realice un programa que lea tres números reales y determine cuál es el mayor.**
"""

numero1 = float(input("Ingrese el primer número: "))
numero2 = float(input("Ingrese el segundo número: "))
numero3 = float(input("Ingrese el tercer número: "))

# Determina cuál es el mayor
if numero1 >= numero2 and numero1 >= numero3:
    mayor = numero1
elif numero2 >= numero1 and numero2 >= numero3:
    mayor = numero2
else:
    mayor = numero3

# Imprime el resultado
print("El número mayor es:", mayor)

"""**Realice un programa que lea dos números reales y determine si el primero es múltiplo del segundo.**"""

numero1 = float(input("Ingrese el primer número:"))
numero2 = float(input("Ingrese el segundo número:"))

if numero1 % numero2 == 0:
  print(numero1, "es múltiplo del segundo número")

else:
  print(numero1,"no es múltiplo del segundo número")

"""**Escriba un programa que solicite al usuario una letra y determine si es una vocal o una consonante.**"""

letra = str(input("Ingrese una letra: "))

letra = letra.lower()

if letra in ('a', 'e', 'i', 'o', 'u'):
    print(letra, " es una vocal.")
else:
    print(letra, "es una consonante.")

"""**Escriba un programa al que se le ingrese la frecuencia de una onda en hz y como salida arroje en que parte del espectro electromagnético se encuentra .**"""

# Solicita al usuario ingresar la frecuencia en Hz
frecuencia = float(input("Ingrese la frecuencia en Hz: "))

# Determina en qué parte del espectro electromagnético se encuentra la frecuencia
if 3e23 < frecuencia < 3e25:
    print("La frecuencia está en la parte de los rayos gamma.")
elif 3e19 < frecuencia <= 3e23:
    print("La frecuencia está en la parte de los rayos X.")
elif 4.3e14 < frecuencia <= 3e19:
    print("La frecuencia está en la parte de los rayos ultravioleta.")
elif 7.5e11 < frecuencia <= 4.3e14:
    print("La frecuencia está en la parte del espectro visible.")
elif 3e9 < frecuencia <= 7.5e11:
    print("La frecuencia está en la parte de las ondas de radio.")
else:
    print("La frecuencia está fuera del espectro electromagnético conocido.")

"""**Escriba un programa que dada una distancia calcula:**

**El tiempo que le tomaría a la luz recorrer la distancia.**

**El tiempo que le tomaría al sonido (en el aire) recorrer la distancia.**

**El tiempo que le tomaría al vehículo comercial más veloz recorrer la distancia.**

**El tiempo que le tomaría a Bolt recorrer la distancia.**
"""

# Definimos las velocidades en metros por segundo

velocidad_luz = 299792458  # m/s
velocidad_sonido = 343  # m/s (en el aire)
velocidad_vehiculo_comercial = 97.2  # m/s (aprox. 350 km/h)
velocidad_bolt = 12.42  # m/s (aprox. 44.72 km/h)

# Solicitamos al usuario ingresar la distancia en metros

distancia = float(input("Ingrese la distancia en metros: "))

# Calculamos los tiempos en segundos

tiempo_luz = distancia / velocidad_luz
tiempo_sonido = distancia / velocidad_sonido
tiempo_vehiculo_comercial = distancia / velocidad_vehiculo_comercial
tiempo_bolt = distancia / velocidad_bolt

# Imprimimos los resultados
print("Tiempo que tomaría a la luz recorrer la distancia:", tiempo_luz, "segundos")
print("Tiempo que tomaría al sonido recorrer la distancia:", tiempo_sonido, "segundos")
print("Tiempo que tomaría al vehículo comercial más veloz recorrer la distancia:", tiempo_vehiculo_comercial, "segundos")
print("Tiempo que tomaría a Usain Bolt recorrer la distancia:", tiempo_bolt, "segundos")